### ISSUE TITLE
non_free_region_index_limit_可以删去，在代码中没有起到作用

### ISSUE THREAD

**Issue by banshanlu** [alibaba/Patrons#10]
[/art/runtime/gc/space/region_space.h]
```
761   // Invariant (verified by RegionSpace::VerifyNonFreeRegionLimit):
762   //   for all `i >= non_free_region_index_limit_`, `regions_[i].IsFree()` is true.
763   size_t non_free_region_index_limit_ GUARDED_BY(region_lock_);
```
non_free_region_index_limit_注释中的`invariant`并非表示这个变量是不变量，注意后面的引号，它指的是762行这个关系式是不变的。实际上non_free_region_index_limit_会在每次CC Collector的ReclaimPhase更新(如下代码所示)，每次回收后都会更新。
而我注意到代码中并没有对non_free_region_index_limit_实时更新，只在init阶段赋值，因此代码中记录的non_free_region_index_limit_是滞后的。

[/art/runtime/gc/collector/concurrent_copying.cc]
```
2743     {
2744       TimingLogger::ScopedTiming split4("ClearFromSpace", GetTimings());
2745       region_space_->ClearFromSpace(&cleared_bytes, &cleared_objects, /*clear_bitmap*/ !young_gen_);
```

其实我明白你是为了防止new_size小于Java堆中已用空间的情况。但这种情况已经在RegionSpace::ClampGrowthLimit中的790行做了处理，所以不必担忧。而这个项目里的non_free_region_index_limit_可以删去，因为没有动态更新的话，这个变量的值也就失去了意义。

[/art/runtime/gc/space/region_space.cc]
```
786 void RegionSpace::ClampGrowthLimit(size_t new_capacity) {
787   MutexLock mu(Thread::Current(), region_lock_);
788   CHECK_LE(new_capacity, NonGrowthLimitCapacity());
789   size_t new_num_regions = new_capacity / kRegionSize;
790   if (non_free_region_index_limit_ > new_num_regions) {
791     LOG(WARNING) << "Couldn't clamp region space as there are regions in use beyond growth limit.";
792     return;
793   }
```

**Comment by zhi1ong** [comment]
patrons 代码里 non_free_region_index_limit_ 是指针，不是在 init 赋值一次，每次使用会取值的。

依赖 RegionSpace::ClampGrowthLimit 的判断，一方面在 <8 的时候没有，另一方面优先自己判断风险可控。

**Comment by banshanlu** [comment]
> patrons 代码里 non_free_region_index_limit_ 是指针，不是在 init 赋值一次，每次使用会取值的

多谢指教，这里我没注意到它是指针，不好意思！👍
