### ISSUE TITLE
怪不得淘宝这么卡

### ISSUE THREAD

**Issue by michaellee123** [alibaba/Patrons#13]
这东西治标不治本的

**Comment by michaellee123** [comment]
然而我默默的点了🌟

**Comment by zhi1ong** [comment]
卡不卡和 Patrons 关系不大，淘宝是双架构的，大部分都是 64 位，也用不到 Patrons，Patrons 主要是压缩了本来也用不到 java 堆空间，换言之就是即使不压缩，java 堆用不到一半的时候，就已经因为地址空间不足 oom crash 了。

确实不治本，直接切64位就完事儿了，让你过渡的更容易一点。
