### ISSUE TITLE
压缩Region Space的地址空间会对Java堆内存分配造成影响吧？

### ISSUE THREAD

**Issue by liuling07** [alibaba/Patrons#15]
压缩Region Space的地址空间会对Java堆内存分配造成影响吧？
我在demo中尝试压缩到274M之后，然后在Java堆上分配对象，Java堆到160M之后就崩溃了。
![image](https://user-images.githubusercontent.com/10380641/140489642-6e0c165b-7826-47c6-9632-d64c0035d9f6.png)

**Comment by zhi1ong** [comment]
会呀，Region Space 可以简单的理解就是 Java 堆，压缩他的前提是如果你突然内存爆发式增长，java 堆还没怎么用就挂了。所以这个不能上来就压缩到 200m，是一个循序渐进的过程。
