### ISSUE TITLE
反编译工具咨询

### ISSUE THREAD

**Issue by pengood** [alibaba/Patrons#19]
https://www.infoq.cn/article/bvbf3iwjztvem4szamvw
![image](https://user-images.githubusercontent.com/8555278/149291780-f9ebd005-0c12-4210-a4d5-07bc70fb96f3.png)

请问大佬，这个文章中的反编译工具是什么啊？好像不是ida

**Comment by zhi1ong** [comment]
NSA 的 ghidra 

https://github.com/NationalSecurityAgency/ghidra
