### ISSUE TITLE
是否仅对64位架构的大RAM手机运行32位应用的场景有效果？

### ISSUE THREAD

**Issue by yangjiantao** [alibaba/Patrons#21]
1. 对于32位的低端设备（RAM较小）本身物理内存不多，缩减RegionSpace仅仅是把有限的空间让给了Native，而Java堆可分配的内存就相应变小了吧
2. 对于64位高端设备，在运行32位应用时，是由于虚拟内存限制在4G以内，导致其无法利用手机空闲的内存，该方案可以多利用部分空间（对应缩减RegionSpace的内存大小）

该方案较适用于：32位且native内存申请较多的应用，特别是运行在64位设备的场景，这样理解对吗

**Comment by zhi1ong** [comment]
Patrons 解决的是虚拟内存的问题，和物理内存大小关系不大，32位应用运行在32位还是64位兼容模式下能用的虚拟内存都是4G，对大型32位应用有不错的效果，把更多的地址空间让给native申请

**Comment by yangjiantao** [comment]
感谢，经验证运行在32位2G设备还是有一定效果。
