### ISSUE TITLE
只能缓解崩溃吧，另外对gc 速度是否有影响

### ISSUE THREAD

**Issue by liminwanqing** [alibaba/Patrons#6]
我的理解是只能缓解崩溃，检测到vss临界点的时候减少region space大小，但是vss仍然是增加，会再次达到大小region space。
但是不能达到就会减少region space大小

另外art gc会不会受到影响，因为目前art gc 几种gc策略都在用，空间减少可能会受到影响吧

**Comment by zhi1ong** [comment]
效果确实是缓解，压缩 Region Space 之后会释放出一部分地址空间，这部分会被 libc malloc 使用，VSS 短时间内不会增加，直到新释放的空间再次用完，不过目前大部分应用都不会常驻后台，相当于只要坚持到生命周期结束之前没有达到 VSS 上限就足够了

gc 不会受到影响，前台主要是 cc，1gb 远远用不到的
