### ISSUE TITLE
伪装libart相同命名空间等相关问题

### ISSUE THREAD

**Issue by whuthj** [alibaba/Patrons#7]
1. 伪装命名空间问题
// 找到 libart 中调用的 libartbase.so 中的方法 GetCmdLine, 没有特殊含义，仅仅是用来找一个和 libart.so 同一命名空间的函数来伪装身份
    xhook_register(".*/libart.so$", "_ZN3art10GetCmdLineEv", NULL, (void **) (&stub_method_in_art),
                   NULL);

    LOGE("stub_method_in_art:%p", stub_method_in_art);

这里打印了stub_method_in_art发现是null，这个对于后面调用libart会不会有影响，实际上测试又看到是有效果的

2. 看到HandleSignal(SIGSEGV)这个会不会影响崩溃捕捉

**Comment by whuthj** [comment]
第二个问题看到sigsetjmp和siglongjmp的处理了

**Comment by whuthj** [comment]
不过第二个还是有一些小问题，就是如果其他线程崩溃了（SIGSEGV），这里HandleSignal也会拦截到，那么可能会导致其他线程崩溃被吞没了，可能引发一些其他问题

**Comment by zhi1ong** [comment]
1. 尽量拿，真要是没有就用 libz 里的一个函数指针，真要是都不对，也没关系，本来也不需要保证 100% 兼容，线上情况看几乎没有拿不到这个的。

2. 劫持信号的处理函数里会做判断，有一个 flag，如果不是我自己引发的信号会交还给原本的信号处理器处理。

**Comment by zhi1ong** [comment]
@whuthj 刚刚没细看，有点答错了，我以为你要问如果真没有这个方法(GetCmdLine)怎么办，你这里打印不出来是因为这里还没赋值，要等 xhook_refresh 执行之后才会赋值的。
